config/routes.rb
Shopping::Application.routes.draw do
  get "store/index"

  resources :products

  root :to => 'store#index', :as => 'store'

end

app/models/product.rb
#---
# Excerpted from "Agile Web Development with Rails, 4rd Ed.",
# published by The Pragmatic Bookshelf.
# Copyrights apply to this code. It may not be used to create training material, 
# courses, books, articles, and the like. Contact us if you are in doubt.
# We make no guarantees that this code is fit for any purpose. 
# Visit http://www.pragmaticprogrammer.com/titles/rails4 for more book information.
#---
class Product < ActiveRecord::Base
  default_scope :order => 'title'
  
  validates :title, :description, :image_url, :presence => true
  validates :price, :numericality => {:greater_than_or_equal_to => 0.01}
# 
  validates :title, :uniqueness => true
  validates :image_url, :format => {
    :with    => %r{\.(gif|jpg|png)$}i,
    :message => 'must be a URL for GIF, JPG or PNG image.'
  }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  # GET /products
  # GET /products.xml
  def index
    @products = Product.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @products }
    end
  end

  # GET /products/1
  # GET /products/1.xml
  def show
    @product = Product.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @product }
    end
  end

  # GET /products/new
  # GET /products/new.xml
  def new
    @product = Product.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @product }
    end
  end

  # GET /products/1/edit
  def edit
    @product = Product.find(params[:id])
  end

  # POST /products
  # POST /products.xml
  def create
    @product = Product.new(params[:product])

    respond_to do |format|
      if @product.save
        format.html { redirect_to(@product, :notice => 'Product was successfully created.') }
        format.xml  { render :xml => @product, :status => :created, :location => @product }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @product.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /products/1
  # PUT /products/1.xml
  def update
    @product = Product.find(params[:id])

    respond_to do |format|
      if @product.update_attributes(params[:product])
        format.html { redirect_to(@product, :notice => 'Product was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @product.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.xml
  def destroy
    @product = Product.find(params[:id])
    @product.destroy

    respond_to do |format|
      format.html { redirect_to(products_url) }
      format.xml  { head :ok }
    end
  end
end

app/controllers/store_controller.rb
 class StoreController < ApplicationController
    def index
      @products = Product.all
    end
  end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/store_helper.rb
module StoreHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>GouWuKuang</title>
    <%= stylesheet_link_tag "scaffold" %>
    <%= stylesheet_link_tag "shopping", :media => "all" %>
    <%= javascript_include_tag :defaults %>
    <%= csrf_meta_tag %>
</head>
<body id="store">
    <div id="banner">
        <%= image_tag("logo.png") %>
        <%= @page_title || "购物狂" %>
    </div>
    <div id="columns">
        <div id="side">
            <a href="http://localhost:3000/">Home</a>
            <br />
            <a href="http://www..../faq">Questions</a>
            <br />
            <a href="http://www..../news">News</a>
            <br />
            <a href="http://www..../contact">Contact</a>
            <br />
        </div>
	
        <div id="main">
			<div id="navi">
			<u1>
				<li><a>首页</a></li>
			    <li><a>我的宝贝</a></li>
				<li><a>好友的宝贝</a></li>
				<li><a>宝贝库</a></li>
			</u1>
			</div>
			<div id="content">
            <%= yield %>
			</div>
        </div>
    </div>
</body>
</html>

app/views/products/_form.html.erb
<%= form_for(@product) do |f| %>
  <% if @product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
      <% @product.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :image_url %><br />
    <%= f.text_field :image_url %>
  </div>
  <div class="field">
    <%= f.label :price %><br />
    <%= f.text_field :price %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/products/edit.html.erb
<h1>Editing product</h1>

<%= render 'form' %>

<%= link_to 'Show', @product %> |
<%= link_to 'Back', products_path %>

app/views/products/index.html.erb
<div id="product_list">
<h1>Listing products</h1>

<table>
<% @products.each do |product| %>
    <tr class="<%= cycle('list_line_odd', 'list_line_even') %>">
        <td>
            <%= image_tag(product.image_url, :class => 'list_image') %>
        </td>
        <td class="list_description">
            <dl>
                <dt><%= product.title %></dt>
                <dd><%= truncate(strip_tags(product.description),
                    :length => 80) %></dd>
            </dl>
        </td>
        <td class="list_actions">
            <%= link_to 'Show', product %><br/>
            <%= link_to 'Edit', edit_product_path(product) %><br/>
            <%= link_to 'Destroy', product, :confirm => 'Are you sure?', :method => :delete %>
        </td>
  </tr>
<% end %>
</table>
</div>
<br />

<%= link_to 'New Product', new_product_path %>

app/views/products/new.html.erb
<h1>New product</h1>

<%= render 'form' %>

<%= link_to 'Back', products_path %>

app/views/products/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Title:</b>
  <%= @product.title %>
</p>

<p>
  <b>Description:</b>
  <%= @product.description %>
</p>

<p>
  <b>Image url:</b>
  <%= @product.image_url %>
</p>

<p>
  <b>Price:</b>
  <%= @product.price %>
</p>


<%= link_to 'Edit', edit_product_path(@product) %> |
<%= link_to 'Back', products_path %>

app/views/store/index.html.erb
<% if notice %>
<p id="notice">
  <%= notice %>
</p>
<% end %>
<h1>Your Pragmatic Catalog</h1>
<% @products.each do |product| %>
<div class="entry">
  <%= image_tag(product.image_url) %>
  <h3><%= product.title %></h3>
  <%= sanitize product.description %>
  <div class="price_line">
    <span class="price"><%= number_to_currency(product.price) %></span>
  </div>
</div>
<% end %>